plugins {
    id 'multiloader-common'
    id 'net.fabricmc.fabric-loom'
    //id 'net.neoforged.moddev'
}
/*
neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    //parchment {
    //    minecraftVersion = parchment_minecraft
    //    mappingsVersion = parchment_version
    //}
}*/

def protocolVersion = protocols_use_local_build == "true" ? protocols_local_version : protocols_version

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    compileOnly("org.spongepowered:mixin:0.8.7")
    compileOnly("org.ow2.asm:asm-tree:9.6")
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly("io.github.llamalad7:mixinextras-common:0.4.1")
    annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1")

    api("maven.modrinth:entity-model-features:${emf_version}")
    api("maven.modrinth:entitytexturefeatures:${etf_version}")
    api("maven.modrinth:entityculling:${entityculling_version}")
    //modApi("maven.modrinth:paperdoll:${paperdoll_version}")

    implementation("net.fabricmc.fabric-api:fabric-api:${fabric_version}")
    implementation("me.shedaniel.cloth:cloth-config-neoforge:${clothconfig_version}")

    implementation("com.github.NiFeather:feathermorph-protocols:${protocolVersion}")
    implementation("com.github.NiFeather:feathermorph-command-compat-layer:${compat_layer_version}")
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}